### ISSUE TITLE
bug with unicode

### ISSUE THREAD

**Issue by reza1615** [fabianp/memory_profiler#113]
I ran memory_profiler on a python code which had unicode text inside it and the code shows this error
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/data/project/checkdictation-fa/www/python/venv/lib/python2.7/site-packages/memory_profiler.py", line 992, in <module>
    show_results(prof, precision=options.precision, stream=out_file)
  File "/data/project/checkdictation-fa/www/python/venv/lib/python2.7/site-packages/memory_profiler.py", line 621, in show_results
    stream.write(unicode(tmp))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xdb in position 53: ordinal not in range(128)
```
I changed line 621
`    stream.write(unicode(tmp))`
to
`    stream.write(unicode(tmp,'UTF-8'))`
and and it is ok please solve this bug

**Comment by fabianp** [comment]
Hi!

Thanks for your report. Could you help to make a reproducible example (so it can be added to the tests)? I've tried the following:

```
@profile
def test_unicode():
    # test when unicode is present
    β = 0
    return

if __name__ == '__main__':
    # run only for Python 3
    test_unicode()
```

but it seems to run fine when run with ```python -m memory_example test.py``` .

**Comment by reza1615** [comment]
`#!/usr/bin/python
# -*- coding: utf-8  -*-
@profile
def test_unicode(txt):
    # test when unicode is present
    txt=txt.replace(u'ی',u'ي')
    return txt
print test_unicode(u'ایست')`

when I run this code like `python -m memory_profiler foo.py`
It will show this error

```
$ python -m memory_profiler foo.py
ايست
Filename: foo.py

Line #    Mem usage    Increment   Line Contents
================================================
     3   10.117 MiB    0.000 MiB   @profile
     4                             def test_unicode(txt):
     5                                 # test when unicode is present
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/data/project/checkdictation-fa/www/python/venv/lib/python2.7/site-packages/memory_profiler.py", line 992, in <module>
    show_results(prof, precision=options.precision, stream=out_file)
  File "/data/project/checkdictation-fa/www/python/venv/lib/python2.7/site-packages/memory_profiler.py", line 621, in show_results
    stream.write(unicode(tmp))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xdb in position 57: ordinal not in range(128)

```

**Comment by fabianp** [comment]
Thanks! The issue should be fixed in current master.

**Comment by Eheran1** [comment]
I get this bug at the very fist instance of a special character:
```
(base) C:\Users\me\.spyder-py3>mprof run "myfile V2.36.py"
mprof: Sampling memory every 0.1s
running new process
running as a Python program...
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\lib\site-packages\memory_profiler.py", line 1303, in <module>
    exec_with_profiler(script_filename, prof, args.backend, script_args)
  File "C:\ProgramData\Anaconda3\lib\site-packages\memory_profiler.py", line 1204, in exec_with_profiler
    exec(compile(f.read(), filename, 'exec'), ns, ns)
  File "myfile V2.36.py", line 277
    GasdurchstrÃ¶mt = 1          # nimmt das Gas WÃ¤rme auf?
                ^
SyntaxError: invalid character '¶' (U+00B6)
```

It should say `Gasdurchströmt = 1`. First line of my program: `# -*- coding: utf-8 -*-`
