### ISSUE TITLE
Cannot import name array2d

### ISSUE THREAD

**Issue by gkoundi** [fabianp/memory_profiler#129]
Following is the output of pip freeze in virualenv.
pip freeze
memory-profiler==0.41
numpy==1.11.2
psutil==5.0.0
scikit-learn==0.18.1
scipy==0.18.1

Following is the error.
mprof run --python run_profile_fast_dot.py
mprof: Sampling memory every 0.1s
running as a Python program...
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/gkoundi/Documents/venv/lib/python2.7/site-packages/memory_profiler-0.41-py2.7.egg/memory_profiler.py", line 982, in <module>
    exec_with_profiler(script_filename, prof)
  File "/Users/gkoundi/Documents/venv/lib/python2.7/site-packages/memory_profiler-0.41-py2.7.egg/memory_profiler.py", line 917, in exec_with_profiler
    execfile(filename, ns, ns)
  File "run_profile_fast_dot.py", line 20, in <module>
    from sklearn.utils.validation import array2d
ImportError: cannot import name array2d

**Comment by fabianp** [comment]
does the script run without mprof, i.e. if you run it as python run_profile_fast_dot.py ?

**Comment by gkoundi** [comment]
No. The issue was in the script. You can close this issue.
