### ISSUE TITLE
Getting a pickling error if I use the decorator in the multiprocessing example

### ISSUE THREAD

**Issue by petroslamb** [fabianp/memory_profiler#148]
Hi,

I'm very much interested in using the profiler to record timestamps for child processes, but haven't managed it yet. 

For starters recording function timestamps with the decoratro in a single process program for me requires the `--python python2` flag, other wise I get the old:

```
NameError: name 'profile' is not defined
```

So, to have this timestamps for child processes in a multiprocess setting I modified the `multiprocessing_example.py` and added a `@profile` over the `worker` function, like so:

```python
@profile
def worker(num, wait, amt=X6):
     """
     A function that allocates memory over time.                                                                                                                                     
     """
     frame = []
 
     for idx in range(num):
         frame.extend([1] * amt)
         time.sleep(wait)
 
     del frame
```

Then I run it and get the other classic:
```
$ mprof run -M --python python2 test_multi.py
mprof: Sampling memory every 0.1s
running as a Python program...
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
...
  File "test_multi.py", line 52, in main_multiproc
    results = [p.get() for p in tasks]
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 558, in get
    raise self._value
cPickle.PicklingError: Can't pickle <type 'function'>: attribute lookup __builtin__.function failed
```
This error does not appear if I drop the `@profile` decorator and the `--python python2` flag that discovers it.

My version is `0.47` and I am using `psutil` in an almost clean virtualenv with minimum packages installed.

Any help most welcome and thanks for your good work.

**Comment by petroslamb** [comment]
Edited to make some corrections above, most on typos but the actual run that failed was with the `-C` flag included. 

It would be great to be able to have timestamps on the children workers. If this is not supported, which part should I focus my attention on, in order to implement it?

**Comment by petroslamb** [comment]
I have made some progress when using the line-by-line memory profiling method, by importing `profile` from `memory_profiler`. Still no luck with the `timestamps` of the decorated function in the child processes.

To avoid the `PicklingError` in the first case one must modify the code of the `multiprocessing_example.py` like so:

```python
def _worker(num, wait, amt=X6):
    """
    A function that allocates memory over time.
    """
    frame = []                                                                                                                                                                      

    for idx in range(num):
        frame.extend([1] * amt)
        time.sleep(wait)

    del frame

decorated_worker = profile(_worker)

def worker(*args, **kwargs):
    return decorated_worker(*args, **kwargs)

```
and run it with:

```
$ mprof run -M test_multi.py

mprof: Sampling memory every 0.1s
Filename: test_multi.py

Line #    Mem usage    Increment   Line Contents
================================================
    16      8.1 MiB      0.0 MiB   def _worker(num, wait, amt=X6):
    17                                 """
    18                                 A function that allocates memory over time.
    19                                 """
    20      8.1 MiB      0.0 MiB       frame = []
    21                             
    22    389.7 MiB    381.6 MiB       for idx in range(num):
    23    389.7 MiB      0.0 MiB           frame.extend([1] * amt)
    24    389.7 MiB      0.0 MiB           time.sleep(wait)
    25                             
    26      8.2 MiB   -381.5 MiB       del frame
...
```

**Comment by fabianp** [comment]
Thanks @petroslamb for the detailed report, I'll look into it ASAP.

**Comment by fabianp** [comment]
Hi @petroslamb ,

I spent some time on this today but unfortunately I don't have a good solution: as you already know adding the decorator makes the function unpicklable, which breaks the multiprocessing code. Unfortunately I don't see a workaround around this one ...

**Comment by Juanlu001** [comment]
This article from 2009 mentions `functools.wraps`, perhaps this is related to #186?

**Comment by Juanlu001** [comment]
Sorry, article link: http://gael-varoquaux.info/programming/decoration-in-python-done-right-decorating-and-pickling.html

**Comment by Colelyman** [comment]
Thanks for the article link @astrojuanlu! I was able to get this to work by following the suggestion in the article.

Using the example from earlier, instead of doing:
```
@profile
def worker(...
```

I did this:
```
profile_worker = profile(worker)
```
and then replace every instance where I call `worker` with `profile_worker`.
