### ISSUE TITLE
memory_usage hangs on exception

### ISSUE THREAD

**Issue by mhaseebtariq** [fabianp/memory_profiler#152]
While executing a method (decorated with `memory_usage`) if there is an exception - the process just hangs without exiting. The scenario can be reproduced using this script:

```
import psutil  # 5.2.0
from memory_profiler import memory_usage  # 0.47'


def foo():
    raise Exception('Error')


memory_usage((foo, tuple(), {}), timeout=1)

```

Only when you press ctrl+c - you can exit the process and see where exactly the process is stuck at:
```
python reproduce.py 


Traceback (most recent call last):
  File "reproduce.py", line 9, in <module>
    memory_usage((foo, tuple(), {}), timeout=1)
  File "/.../python3.5/site-packages/memory_profiler.py", line 334, in memory_usage
    returned = f(*args, **kw)
  File "reproduce.py", line 6, in foo
    raise Exception('Error')
Exception: Error

^C

Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/.../python3.5/multiprocessing/popen_fork.py", line 29, in poll
Process MemTimer-1:
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
Traceback (most recent call last):
  File "/.../python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/.../python3.5/site-packages/memory_profiler.py", line 235, in run
    stop = self.pipe.poll(self.interval)
  File "/.../python3.5/multiprocessing/connection.py", line 257, in poll
    return self._poll(timeout)
  File "/.../python3.5/multiprocessing/connection.py", line 414, in _poll
    r = wait([self], timeout)
  File "/.../python3.5/multiprocessing/connection.py", line 911, in wait
    ready = selector.select(timeout)
  File "/.../python3.5/selectors.py", line 376, in select
    fd_event_list = self._poll.poll(timeout)
KeyboardInterrupt

```

Tested on macOS 10.12.6 and CentOS - **Python 3.5**

**Comment by mhaseebtariq** [comment]
A possible workaround!

```
import traceback
import os
from signal import SIGKILL

import psutil
from memory_profiler import memory_usage 


def foo():
    raise Exception('Error')


try:
    usage = memory_usage((foo, tuple(), {}), timeout=1)
except Exception as error:
    exception = traceback.format_exc()
    LOGGER.error(exception)
    parent = psutil.Process(os.getpid())
    for child in parent.children(recursive=True):
        os.kill(child.pid, SIGKILL)
    os.kill(os.getpid(), SIGKILL)
```

**Comment by fabianp** [comment]
Nice!

Could you submit a patch implementing this strategy in memory_usage ? You'll likely need to add this try/catch strategy around [line 334 of memory_profiler.py](https://github.com/fabianp/memory_profiler/blob/master/memory_profiler.py#L334)

**Comment by mhaseebtariq** [comment]
Sure thing! :) I will try to produce a patch. Thanks!

**Comment by mhaseebtariq** [comment]
Hi @fabianp here you go! :) https://github.com/fabianp/memory_profiler/pull/154/files

**Comment by mhaseebtariq** [comment]
@fabianp I am closing this issue now!
