### ISSUE TITLE
Not able to plot the graph from "./mplot run"

### ISSUE THREAD

**Issue by kumarvikas2605** [fabianp/memory_profiler#91]
I've done "mprof run --python <script-name>" and post that I am trying to plot the graph("mprof plot"). But I don't see any graph being plotted.

vikas@host:/home/vikas/memory_profiler-0.32$ ./mprof run --python ../asl
mprof: Sampling memory every 0.1s

running as a Python program...

vikas@host:/home/vikas/memory_profiler-0.32$ cat mprofile_20150224005550.dat

CMDLINE python ../asl

MEM 1.316406 1424768150.5671

MEM 6.539062 1424768150.6675

MEM 8.812500 1424768150.7678

MEM 8.812500 1424768150.8681

MEM 8.812500 1424768150.9684

**Comment by fabianp** [comment]
Hi,

once the command ``mprof run --python``has finished, you need to run ``mprof plot`` to see the result.

Does that work ?

**Comment by kumarvikas2605** [comment]
Their was some issue in the f*.dat file.
I tried fresh(./mprof plot) and I was able to see this:
mprofile: {'cmd_line': 'python mprof_script\n', 'timestamp': [1424853646.7537, 1424853646.8541, 1424853646.9544001, 1424853647.0548, 1424853647.1551001, 1424853647.2553999, 1424853647.3557999, 1424853647.4561, 1424853647.5565, 1424853647.6568, 1424853647.7572, 1424853647.8576, 1424853647.9579999, 1424853648.0583999, 1424853648.1587, 1424853648.2591], 'func_timestamp': {}, 'mem_usage': [0.99218799999999996, 6.515625, 8.8203119999999995, 8.8203119999999995, 8.8203119999999995, 8.8203119999999995, 8.8203119999999995, 8.8203119999999995, 8.8203119999999995, 8.8203119999999995, 8.8203119999999995, 8.8203119999999995, 8.8203119999999995, 8.8203119999999995, 8.8203119999999995, 8.8203119999999995], 'filename': 'mprofile_20150225004046.dat'}

But is this the expected o/p?
I though it should also include some graph?

**Comment by fabianp** [comment]
The graph is created from the *.dat file once you execute the command ``./mprof plot``. What is the output of this command ?

**Comment by kumarvikas2605** [comment]
vikas@host$ ./mprof plot
mprofile: {'cmd_line': 'python mprof_script\n', 'timestamp': [1424855029.7542, 1424855029.8546, 1424855029.9549, 1424855030.0552001, 1424855030.1556001, 1424855030.2558999, 1424855030.3562, 1424855030.4566, 1424855030.5569999, 1424855030.6573999, 1424855030.7578001], 'func_timestamp': {}, 'mem_usage': [1.316406, 8.1171880000000005, 8.8203119999999995, 8.8203119999999995, 8.8203119999999995, 8.8203119999999995, 8.8203119999999995, 8.8203119999999995, 8.8203119999999995, 8.8203119999999995, 8.8242189999999994], 'filename': 'mprofile_20150225010349.dat'}

**Comment by kumarvikas2605** [comment]
I take back my previous comment... it is not plotting anything when I run ./mprof plot.... no output at all.

The above output of ./mprof plot has come because I have printed the profile in the method:plot_file() of mprof:
def plot_file(filename, index=0, timestamps=True):
    try:
        import pylab as pl
    except ImportError:
        print("matplotlib is needed for plotting.")
        sys.exit(1)
    import numpy as np  # pylab requires numpy anyway
    mprofile = read_mprofile_file(filename)
    print 'mprofile: %s' % mprofile

So it seems to be a valid bug.

**Comment by fabianp** [comment]
Indeed, it looks like a bug. Thanks for the report. I'll look into it ASAP

**Comment by kumarvikas2605** [comment]
One more observation. When I run "./mprof plot" on my local terminal I get the graph plotted.
But when I run the same command on a remote server I get: "RuntimeError: could not open display"

(process:13349): Gtk-WARNING **: Locale not supported by C library.
        Using the fallback 'C' locale.
Traceback (most recent call last):
  File "./mprof", line 472, in <module>
    actions[get_action()]()
  File "./mprof", line 391, in plot_action
    import pylab as pl
  File "/usr/lib64/python2.6/site-packages/pylab.py", line 1, in <module>
    from matplotlib.pylab import *
  File "/usr/lib64/python2.6/site-packages/matplotlib/pylab.py", line 247, in <module>
    from matplotlib.pyplot import *
  File "/usr/lib64/python2.6/site-packages/matplotlib/pyplot.py", line 78, in <module>
    new_figure_manager, draw_if_interactive, show = pylab_setup()
  File "/usr/lib64/python2.6/site-packages/matplotlib/backends/__init__.py", line 25, in pylab_setup
    globals(),locals(),[backend_name])
  File "/usr/lib64/python2.6/site-packages/matplotlib/backends/backend_gtkagg.py", line 10, in <module>
    from matplotlib.backends.backend_gtk import gtk, FigureManagerGTK, FigureCanvasGTK,\
  File "/usr/lib64/python2.6/site-packages/matplotlib/backends/backend_gtk.py", line 8, in <module>
    import gtk; gdk = gtk.gdk
  File "/usr/lib64/python2.6/site-packages/gtk-2.0/gtk/__init__.py", line 64, in <module>
    _init()
  File "/usr/lib64/python2.6/site-packages/gtk-2.0/gtk/__init__.py", line 52, in _init
    _gtk.init_check()
RuntimeError: could not open display

I guess this is something to do with X server display. But as a user of memory_profile should I worry about all these things. Shouldn't this be taken care internally?

Meanwhile can you provide me any workaround.... instead of displaying the graph can we save it some "pdf"/"jpeg" or to any other format and the we can open and see.

**Comment by fabianp** [comment]
as a workaround you could try the option --output=file.png so save to file instead of displaying, as in

    ./mprof plot --output=plot.png

**Comment by ftpronk** [comment]
Hi.  I think it has to do with the matplotlib backend.  I have the same issue, using OpenSUSE 13.2

However, when I add:
```python
import matplotlib
matplotlib.use('Qt4Agg')
```
at the very top of the mprof executable (i.e. when choosing th Qt4Agg backend), then `mprof plot` works.  More information can be found [on the matplotlib site](http://matplotlib.org/faq/usage_faq.html#what-is-a-backend). 

Beware of point **4**: _If you use the use() function, this must be done before importing matplotlib.pyplot. Calling use() after pyplot has been imported will have no effect._

**Comment by Thalmann** [comment]
Hi,

I got the error: "matplotlib is needed for plotting.".
The problem for me was that matplotlib uses the module tkinter which raises and ImportError in the matplotlib and this was caught by mprof.
I resolved this by installing tkinter after i had installed matplotlib.

I think maybe you guys had the same error, anyways maybe it should be included in the error message?

**Comment by oolongtea** [comment]
Thanks @Thalmann. `yum install tkinter` fixed this for me on CentOS 7.

**Comment by Juanlu001** [comment]
On the one hand https://github.com/pythonprofilers/memory_profiler/pull/120 was merged, and on the other hand an alternative fix would be setting the `MPLBACKEND` to `Agg` http://matplotlib.org/tutorials/introductory/usage.html#what-is-a-backend
